name: Continous integration for Tomatenquark
on: [push]

env:
  GITCOMMITID: 7027d93e776daf0107de86af64dfcbccab782140

jobs:
  build-macos:
    runs-on: macos-latest
    env:
      vcpkgResponseFile: '${{ github.workspace }}/cmake/triplets/osx'
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: lukka/get-cmake@latest
      - name: Restore from cache and run vcpkg
        uses: lukka/run-vcpkg@v5
        with:
          vcpkgArguments: '@${{ env.vcpkgResponseFile }}'
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: ${{ env.GITCOMMITID }}
          appendedCacheKey: ${{ hashFiles(env.vcpkgResponseFile) }}
      - name: Build for OSX
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake -G Xcode
          xcodebuild clean -arch x86_64 build
  build-windows:
    runs-on: windows-latest
    env:
      vcpkgResponseFile: '${{ github.workspace }}/cmake/triplets/windows64'
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: lukka/get-cmake@latest
      - name: Restore from cache and run vcpkg
        uses: lukka/run-vcpkg@v5
        with:
          vcpkgArguments: '@${{ env.vcpkgResponseFile }}'
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: ${{ env.GITCOMMITID }}
          appendedCacheKey: ${{ hashFiles(env.vcpkgResponseFile) }}
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build for Windows
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake
          msbuild /property:Platform=x64 /t:tomatenquark tomatenquark.sln
  build-ubuntu:
    runs-on: ubuntu-latest
    env:
      vcpkgResponseFile: '${{ github.workspace }}/cmake/triplets/linux64'
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: lukka/get-cmake@latest
      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libasound2-dev libvorbis-dev
      - name: Restore from cache and run vcpkg
        uses: lukka/run-vcpkg@v5
        with:
          vcpkgArguments: '@${{ env.vcpkgResponseFile }}'
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: ${{ env.GITCOMMITID }}
          appendedCacheKey: ${{ hashFiles(env.vcpkgResponseFile) }}
      - name: Build for Ubuntu
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
          make
